Resources:
  TrailRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 
              - cloudtrail.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:eu-west-1:914609264432:log-group::log-stream:914609264432_CloudTrail_eu-west-1*'
  TrailBucket:
    Type: AWS::S3::Bucket
  TrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Statement:
            - 
              Sid: "AWSCloudTrailAclCheck"
              Effect: "Allow"
              Principal: 
                Service: "cloudtrail.amazonaws.com"
              Action: "s3:GetBucketAcl"
              Resource: 
                !Sub |-
                  arn:aws:s3:::${TrailBucket}
            - 
              Sid: "AWSCloudTrailWrite"
              Effect: "Allow"
              Principal: 
                Service: "cloudtrail.amazonaws.com"
              Action: "s3:PutObject"
              Resource:
                !Sub |-
                  arn:aws:s3:::${TrailBucket}/AWSLogs/${AWS::AccountId}/*
              Condition: 
                StringEquals:
                  s3:x-amz-acl: "bucket-owner-full-control"
  BasicTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: TrailBucketPolicy
    Properties:
      EnableLogFileValidation: true
      IsLogging: false
      IsMultiRegionTrail: false
      S3BucketName: !Ref TrailBucket
      #CloudWatchLogsRoleArn: !GetAtt TrailRole.Arn
      EventSelectors:
        - IncludeManagementEvents: true
          DataResources:
            - Type: 'AWS::S3::Object'
              Values: 
                - !Sub 'arn:aws:s3:::${TrailBucket}/'
            - Type: 'AWS::Lambda::Function'
              Values: 
                - 'arn:aws:lambda'

